version: '3'

services:
  php:
    container_name: php
    build: ./lnmp/php
    volumes:
    - ./develop:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ./develop:/var/www
    - ./lnmp/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./lnmp/db/data:/var/lib/mysql
    - ./lnmp/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./lnmp/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306